import type { CallLLM, ChatMessage } from "@/lib/llm/client";
import type { SessionState } from "@/lib/schemas/session";
import { scanBannedPhrases } from "@/lib/prompts/banned-phrases";

/**
 * Summarize the last N turns of a session to help the GM identify a deadlock
 * or stalemate pattern. The summary is generated by the LLM and then scanned
 * for banned sycophantic phrases.
 *
 * This orchestrator is pure — it does not mutate the session store. The caller
 * (route handler) decides what to do with the summary.
 */

export interface SummarizeDeadlockDeps {
  callLLM: CallLLM;
  logger?: (stage: string, err: unknown) => void;
}

export type SummarizeDeadlockResult =
  | { ok: true; summary: string; warnings: string[] }
  | { ok: false; error: string };

export async function summarizeDeadlock(
  session: SessionState,
  lastN: number,
  deps: SummarizeDeadlockDeps
): Promise<SummarizeDeadlockResult> {
  const recentTurns = session.turns.slice(-lastN);
  if (recentTurns.length === 0) {
    return { ok: false, error: "No turns to summarize." };
  }

  const turnsText = recentTurns
    .map((t, i) => {
      if (t.kind === "resolved") {
        return `Turn ${i + 1}: ${t.intent.action} — ${t.result.summary}`;
      }
      if (t.kind === "narration") {
        return `Turn ${i + 1}: [Narration] ${t.markdown.slice(0, 200)}`;
      }
      if (t.kind === "manager-override") {
        return `Turn ${i + 1}: [Manager Override] ${t.forcedOutcome.slice(0, 200)}`;
      }
      return `Turn ${i + 1}: unknown`;
    })
    .join("\n");

  const system = `You are a neutral game state summarizer for a Pathfinder TTRPG session. Summarize the given turns in 2-3 sentences. Identify any deadlock, stalemate, or repetitive pattern. Reference specific actions and outcomes. Be factual and concise. Do not add interpretation beyond what the turns show.`;

  const user = `Summarize these ${recentTurns.length} recent game turns:\n\n${turnsText}`;

  const messages: ChatMessage[] = [{ role: "user", content: user }];

  let raw: string;
  try {
    raw = await deps.callLLM({ system, messages });
  } catch (err) {
    deps.logger?.("summarize-deadlock", err);
    return {
      ok: false,
      error: err instanceof Error ? err.message : "Summarization failed.",
    };
  }

  const bannedHits = scanBannedPhrases(raw);
  const warnings: string[] =
    bannedHits.length > 0
      ? bannedHits.map((phrase) => `Banned phrase detected: "${phrase}".`)
      : [];

  return { ok: true, summary: raw.trim(), warnings };
}
